### ISSUE TITLE
AsyncImageLoadDidFinish doesnt get call if the image is cached

### ISSUE THREAD

**Issue by ivangodfather** [nicklockwood/AsyncImageView#63]
Hi, im adding a subview(1) while loading an image. When the image finished downloading i get a notification (AsyncImageLoadDidFinish). The problem is when the image is already cached that i get no notification, so the method that removes the subview(1) doesnt get fired. Any suggestion?

**Comment by nicklockwood** [comment]
Before setting the image, try:

    if ([[AsyncImageLoader sharedLoader].cache objectForKey:imageURL] == nil) { ... }

And only show your subview when it's true.

**Comment by ivangodfather** [comment]
Awesome! :)

**Comment by matoelorriaga** [comment]
thanks!
